# Generated by Django 4.0.5 on 2022-06-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_banned'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('title', 'video')},
        ),
    ]
